list1=[]
num1=list1.append(int(input("請輸入第 1 個數字:")))
num2=list1.append(int(input("請輸入第 2 個數字:")))
num3=list1.append(int(input("請輸入第 3 個數字:")))
num4=list1.append(int(input("請輸入第 4 個數字:")))
num5=list1.append(int(input("請輸入第 5 個數字:")))
num6=list1.append(int(input("請輸入第 6 個數字:")))
num7=list1.append(int(input("請輸入第 7 個數字:")))
num8=list1.append(int(input("請輸入第 8 個數字:")))
num9=list1.append(int(input("請輸入第 9 個數字:")))
num10=list1.append(int(input("請輸入第 10 個數字:")))
a=list1.sort()
print("最大的3個數字為:",list1[9],",",list1[8],",",list1[7])
print("最小的3個數字為:",list1[2],",",list1[1],",",list1[0])